version: "3.8"

services:
    flask:
        image: getmentorservice
        build:
            context: .
            dockerfile: Dockerfile
        environment:
          APP_PORT: 5000
        volumes:
            - .:/inner_docker
        networks:
            - backend
            - frontend
        depends_on:
            -   mongodb
#        ports:
#            - "5000:5000"

    mongodb:
        image: mongo:5.0.6
        environment:
            - MONGO_DATA_DIR=/data/db
        #    - MONGO_LOG_DIR=/dev/null
        #    - MONGO_INITDB_DATABASE=userservice
        #    - MONGO_INITDB_ROOT_USERNAME=admin
        #    - MONGO_INITDB_ROOT_PASSWORD=admin
        volumes:
        #    - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
            - ./db:/data/db
        networks:
            - backend

    webserver:
        build:
            context: nginx
            dockerfile: Dockerfile
        image: digitalocean.com/webserver:latest
        container_name: webserver
        environment:
            APP_DEBUG: "true"
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - nginxdata:/var/log/nginx
        depends_on:
            - flask
        networks:
            - frontend


networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local
